### PR TITLE
Chore: Budget backend routing for API

### PR DESCRIPTION
**Pull request by vtopham**
Hello dear team!

This PR fulfills this Trello card:
https://trello.com/c/KzC7I3RW

It now allows a user to create, edit, get, and delete a given budget. I suggest in the future we add a "name" field to this table, and then write validation middleware before we move on to testing.

### CODE REVIEW

**Review by chelsabeth — APPROVED** [review]
Looks good 👍

**Review by imriven — APPROVED** [review]
Looks clear and concise!

**Review by chelsabeth — APPROVED** [review]
Linter is fixed 👍 Looks good

**Review by locbgiang — APPROVED** [review]
Approve.

**Review by locbgiang — APPROVED** [review]
Looks good.

**Review by chelsabeth — APPROVED** [review]
Great work! Looks good

**Pull request merged**
