### PR TITLE
Chore/authMiddleware

### PR DESCRIPTION
**Pull request by imriven**
Added Auth Middleware to all routes.
Resolves issue #15 

https://trello.com/c/W7et2dpH/86-transaction-routes-should-be-authenticated

### CODE REVIEW

**Comment by imriven** [comment]
[Transaction Routes should be Authenticated](https://trello.com/c/W7et2dpH/86-transaction-routes-should-be-authenticated)

**Review by Cireimu — APPROVED** [review]

**Review by vtopham — APPROVED** [review]
Looks great! We'll be so authorized!

**Review by chelsabeth — CHANGES_REQUESTED** [review]
Hey Christina, code looks good, but it looks like you have to fix your linter

**Comment by imriven** [comment]
So the auth was commented out that's why I was getting the error. Somebody must have commented it out because with auth not commented out the transaction tests weren't passing. But all that needed to be done was to mock the middleware in the test.

**Review by chelsabeth — APPROVED** [review]
Looks great 😄

**Pull request merged**
